export interface Books {
    id: number,
    title: string,
    description: string,
    image: string,
    price: number,
  }
  const techBooks:Books[] = [
    {
      id: 1,
      title: "Rado",
      description: "Increase Your Style.",
      image: "/images/sh1.jpg",
      price: 39.00,
    },
    {
      id: 2,
      title: "Stavenson",
      description: "Increase Your Style.",
      image: "/images/sh2.jpg",
      price: 40.00,
    },
    {
      id: 3,
      title: "Omega",
      description: "Increase Your Style.",
      image: "/images/sh3.jpg",
      price: 15.00,
    },
    {
      id: 4,
      title: "Omega",
      description: "Increase Your Style.",
      image: "/images/sh5.jpg",
      price: 42.99,
    },
    {
      id: 5,
      title: "Citizen",
      description: "Increase Your Style.",
      image: "/images/sh4.jpg",
      price: 30.00,
    },
    {
      id: 6,
      title: "Rolex",
      description: "Increase Tour Style.",
      image: "/images/sh6.jpg",
      price: 40.99,
    },
    {
      id: 8,
      title: "Stavenson",
      description: "Increase Your Style.",
      image: "/images/sh7.jpg",
      price: 25.99,
    },
    {
      id: 7,
      title: "Omega",
      description: "Increase Your Style.",
      image: "/images/sh8.jpg",
      price: 15.99,
    },
    {
      id: 9,
      title: "Rolex",
      description: "Increase Your Style.",
      image: "/images/sh9.jpg",
      price: 12.99,
    },
    {
      id: 10,
      title: "citizen",
      description: "Increase Your Style.",
      image: "/images/sh10.jpg",
      price: 30.99,
    },
    {
      id: 11,
      title: "Omega",
      description: "Increase Your Style.",
      image: "/images/sh11.jpg",
      price: 15.99,
    },
    {
      id: 12,
      title: "Rolex",
      description: "Increase Your Style.",
      image: "/images/sh12.jpg",
      price: 50.99,
    },
    {
      id: 13,
      title: "Citizen",
      description: "Increase Your Style.",
      image: "/images/sh13.jpg",
      price: 25.99,
    },
    {
      id: 14,
      title: "Rado",
      description: "Increase Your Style.",
      image: "/images/sh14.jpg",
      price: 15.99,
    },
    {
      id: 15,
      title: "Omega",
      description: "Increase Your Style.",
      image: "/images/sh15.jpg",
      price: 20.99,
    },
  ];
  
  export default techBooks;
  